/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HotSearch: typeof import('./../components/HotSearch.vue')['default']
    RefreshSolid: typeof import('./../components/icons/RefreshSolid.vue')['default']
    SettingAltLine: typeof import('./../components/icons/SettingAltLine.vue')['default']
    SettingMenu: typeof import('./../components/SettingMenu.vue')['default']
  }
}
